### PR TITLE
Pass other props through render

### PR DESCRIPTION
**Pull request by b3nj4m**
This allows you to attach event handlers, etc.

```jsx
<Masonry options={...} onScroll={this.handleScroll}>...</Masonry>
```

### CODE REVIEW

**Comment by eiriklv** [comment]
Seems like a good idea @b3nj4m :-) I'll take a closer look asap. Man I wish I had tests for this thing.. :p

**Comment by afram** [comment]
@b3nj4m Cheers for this! It will be part of the 3.x release coming very soon.

**Comment by afram** [comment]
One thing I will do though is switch the render method round a bit slightly so that we don't inadvertently overwrite our refs.

From this:

```js
render: function() {
    return React.createElement(this.props.elementType, extend({
        ref: refName
    }, this.props), this.props.children);
}
```

To this:

```js
render: function() {
    return React.createElement(this.props.elementType, extend(this.props, {ref: refName}), this.props.children);
}
```

**Comment by eiriklv** [comment]
@afram great stuff!

**Pull request merged**
